#!/usr/bin/env python3
"""Paths, target resolution, and the two loaders for this repository's tools.

Three distinct places, on purpose:

  trace     RTM_TRACE: the optimisation run being distilled. Read-only. It is
            itself a git repo, and it is the only source of truth for code and
            for the kept/reverted verdict.
  scratch   RTM_WORKSPACE: parsed jsonl, packets, batch plans. All of it is
            reproducible from the trace, so none of it is committed.
  staging   RTM_STORE: the distilled records plus the reports that justify which
            versions were selected. This is what a reviewer reads.

The staging store is NOT the live store. Records reach
`gpu-wiki/kernel_wiki/records/` only through `skills/wiki-gate`, which is the
only writer: it refuses a duplicate id, appends the index entry, and re-runs the
store's own record-level gates. Writing there directly would bypass all of that.

Environment:

  RTM_TRACE       trace directory (no default: the trace is the argument)
  RTM_TRACE_NAME  key of TRACES below, used only to look up hardware defaults
  RTM_TRACE_ROOT  root the TRACES `path` values are resolved against
  RTM_TRACE_LABEL provenance label for the trace (default: its directory name)
  RTM_WORKSPACE   scratch root      (default /tmp/opt-trace-mining/<slug>)
  RTM_STORE       staging store     (default gpu-wiki/kernel_wiki/staging)
  RTM_VENDOR / RTM_ARCH / RTM_PRODUCT / RTM_DSL / RTM_HARNESS
                  assert the measurement target when the trace does not state it
  RTM_NON_TARGET_KERNELS
                  comma-separated kernel names that a profiler capture may NOT
                  be about (see NON_TARGET_KERNELS)
  ATREX_WIKI_DENYLIST
                  file of private substrings to scrub; read by anonymize.py and
                  by the store's own anonymisation gate
"""
import importlib.util
import os
import re
import subprocess
import sys
import tempfile
from pathlib import Path

SKILL_DIR = Path(__file__).resolve().parent.parent
# The skill lives at <gpu-wiki>/skills/<name>, so the repo area is two levels up.
# Self-locating rather than hard-coded, so the tree can be moved or vendored.
GPU_WIKI = SKILL_DIR.parent.parent
TOOLS = GPU_WIKI / "tools"
KERNEL_WIKI = GPU_WIKI / "kernel_wiki"

# The live store. Read-only from here: used for the dedup/overlap scan and for id
# allocation, never written.
STORE_RECORDS = KERNEL_WIKI / "records"
STORE_INDEX = STORE_RECORDS / "index.json"

SCHEMA_PATH = GPU_WIKI / "schema" / "kernel" / "schema.json"
SCHEMA_NAME = "clean-1.3"

# The corpus profile: clean-1.3 with this pipeline's rules turned into schema.
# Generated by make_schema.py; every deviation is declared in its PATCHES list.
PROFILE_NAME = "opt-trace-1.0"
PROFILE_SCHEMA = SKILL_DIR / "assets" / "schema" / "opt-trace-1.0.schema.json"

BUILDER_VERSION = "opt-trace-0.1"

# --------------------------------------------------------------- trace registry

# ONE EXAMPLE ENTRY, and it is fictional: this repository ships no traces.
# Point RTM_TRACE at your own trace repository, or register it here so its
# hardware does not have to be retyped on every run.
#
# A trace is one git repository capturing successive versions of ONE kernel:
#
#   <trace>/.git                    commit subjects carry the kept/reverted
#                                   verdict; `v<N>:` prefixes name the version
#   <trace>/kernel.py               the kernel as of that commit
#   <trace>/memory/v<N>.json        per-version measurements: this is where
#                                   every number in a record comes from
#   <trace>/profiles/v<N>*/         ncu captures        (optional)
#   <trace>/versions/kernel_v<N>.py kept-version snapshots  (optional)
#   <trace>/definition.json         operator name, axes  (optional)
#   <trace>/solution.json           target hardware, languages  (optional)
#   <trace>/workload.jsonl          one line per benchmarked shape  (optional)
#
# Only `.git` is mandatory. Everything else degrades: no memory/ means no
# numbers, hence no strategy records; no profiles/ means no profiler-backed
# bottleneck may ever be claimed.
TRACES = {
    "example-fused-softmax": {
        "path": "example-traces/kernel_opt_001_example_fused_softmax_h4096",
        "vendor": "nvidia", "arch": "blackwell", "product": "b200",
        "dsl": "triton",
        "harness": "the trace's own benchmark harness",
        "note": "FICTIONAL placeholder so the shape of an entry is visible. "
                "Replace it with your own trace, or ignore the registry and "
                "export RTM_TRACE plus RTM_ARCH / RTM_PRODUCT.",
    },
}

# Product token -> (vendor, arch, product), all three legal values of the
# corresponding schema enums. Used to turn whatever `solution.json` says about
# the target into a scope the store can filter on. Extend as you add hardware.
TARGET_TABLE = {
    "a100": ("nvidia", "ampere", "a100"),
    "h100": ("nvidia", "hopper", "h100"),
    "h200": ("nvidia", "hopper", "h200"),
    "b200": ("nvidia", "blackwell", "b200"),
    "b300": ("nvidia", "blackwell-ultra", "b300"),
    "gb200": ("nvidia", "blackwell", "gb200"),
    "rtx5090": ("nvidia", "blackwell-geforce", "sm120"),
    "sm120": ("nvidia", "blackwell-geforce", "sm120"),
    "mi300x": ("amd", "cdna3", "mi300x"),
    "mi308x": ("amd", "cdna3", "mi308x"),
    "mi355x": ("amd", "cdna4", "mi355x"),
}

# A profiler capture whose summary names one of these measured something other
# than the kernel under test. The default is torch's RNG fill, which runs before
# the operator and is what `ncu` grabs when no --kernel-name filter was passed:
# the resulting metrics files are complete and describe the wrong kernel, so they
# are actively misleading rather than merely empty.
NON_TARGET_KERNELS = tuple(
    k.strip() for k in (os.environ.get("RTM_NON_TARGET_KERNELS")
                        or "distribution_elementwise_grid_stride_kernel").split(",")
    if k.strip())

# ------------------------------------------------------------------ the trace

_trace_arg = os.environ.get("RTM_TRACE") or ""
TRACE_NAME = os.environ.get("RTM_TRACE_NAME") or ""

if not _trace_arg and TRACE_NAME:
    entry = TRACES.get(TRACE_NAME)
    if not entry:
        raise SystemExit("unknown RTM_TRACE_NAME %r; config.TRACES knows: %s"
                         % (TRACE_NAME, ", ".join(sorted(TRACES))))
    root = Path(os.environ.get("RTM_TRACE_ROOT") or ".").expanduser()
    _trace_arg = str((root / entry["path"]).expanduser())

# `Path("")` stringifies to `.`, so "no trace" has to be tracked separately or an
# unset RTM_TRACE silently means the current directory.
TRACE_SET = bool(_trace_arg)
TRACE = Path(_trace_arg).expanduser() if TRACE_SET else Path("")


def trace_entry():
    """The registry entry for this run, or {} when the trace is unregistered."""
    return TRACES.get(TRACE_NAME) or {}


def trace_slug(trace: Path) -> str:
    """`.../001/kernel_opt_001_example_fused_softmax` -> `001-example-fused-softmax`.

    The numeric prefix is kept because it is how humans refer to a benchmarked
    operator, and the rest is the operator name with the redundant
    `kernel_opt_<n>_` stripped.
    """
    name = trace.name
    m = re.match(r"kernel_opt_(\d+)_(.+)$", name)
    if m:
        return "%s-%s" % (m.group(1), m.group(2).replace("_", "-"))
    return re.sub(r"[^\w.-]+", "-", name).strip("-_.").replace("_", "-")


SLUG = trace_slug(TRACE) if TRACE_SET else ""

WORKSPACE = Path(os.environ.get("RTM_WORKSPACE")
                 or Path(tempfile.gettempdir()) / "opt-trace-mining"
                 / (SLUG or "unset")).resolve()
WORK = WORKSPACE / "work"
PACKETS = WORKSPACE / "packets"

# The staging store: distilled records plus the reports that justify them. It is
# a review area, not part of the served store -- nothing reads it at query time,
# and `wiki-gate` copies records out of it into `kernel_wiki/records/`.
STORE = Path(os.environ.get("RTM_STORE") or KERNEL_WIKI / "staging").resolve()
RECORDS = STORE / "records"
REPORTS = STORE / "reports" / (SLUG or "unset")


def require_trace():
    if not TRACE_SET:
        raise SystemExit(
            "set RTM_TRACE to the trace directory (or RTM_TRACE_NAME to a key "
            "of config.TRACES together with RTM_TRACE_ROOT)")
    if not TRACE.is_dir():
        raise SystemExit("no such trace directory: %s" % TRACE)
    if not (TRACE / ".git").exists():
        raise SystemExit(
            "%s has no .git; the kept/reverted verdict lives in the commit "
            "subjects and cannot be recovered without it" % TRACE)


def ensure_dirs():
    for d in (WORK, PACKETS, RECORDS, REPORTS):
        d.mkdir(parents=True, exist_ok=True)


def trace_label() -> str:
    """The provenance label written to `evidence.raw.source_repo`.

    A name, never an absolute path: the record has to stay resolvable after the
    trace is moved, and an absolute path is exactly what the store's
    anonymisation gate rejects. It is human-only anyway -- `raw` never reaches
    the served projection -- but reviewers need it to find the run again.
    """
    return os.environ.get("RTM_TRACE_LABEL") or (TRACE.name if TRACE_SET else "")


def target_from_config():
    """(vendor, arch, product, dsl, harness) as asserted by env or registry.

    Any of them may be None. Detection in `ingest.py` fills the rest and records
    which happened, so a record never claims hardware nobody stated.
    """
    entry = trace_entry()
    return (os.environ.get("RTM_VENDOR") or entry.get("vendor"),
            os.environ.get("RTM_ARCH") or entry.get("arch"),
            os.environ.get("RTM_PRODUCT") or entry.get("product"),
            os.environ.get("RTM_DSL") or entry.get("dsl"),
            os.environ.get("RTM_HARNESS") or entry.get("harness")
            or "the trace's own benchmark harness")


def target_from_token(token):
    """Map one hardware token from the trace onto (vendor, arch, product)."""
    key = re.sub(r"[^a-z0-9]+", "", str(token or "").lower())
    if key in TARGET_TABLE:
        return TARGET_TABLE[key]
    for name, triple in TARGET_TABLE.items():
        if name in key:
            return triple
    return None


def git(*args, cwd=None, timeout=60, input_text=None):
    r = subprocess.run(["git", "-C", str(cwd or TRACE), *args],
                       input=input_text, capture_output=True, text=True,
                       timeout=timeout)
    return r.stdout


def head_sha() -> str:
    return git("rev-parse", "HEAD").strip()


# ------------------------------------------------- this repository's own tools

def _load_tool(name):
    """Import a module from `gpu-wiki/tools/` by path.

    By path rather than by package import because `tools/` is not a package and
    the skill must keep working when the repository is vendored under a
    different name. This is the ONLY way a module outside the skill is loaded,
    and both callers below are in-repo: a missing file means a broken checkout,
    not an optional feature, so it fails with the path it looked for.
    """
    path = TOOLS / ("%s.py" % name)
    if not path.is_file():
        raise SystemExit(
            "%s is missing; this skill is part of gpu-wiki and needs the "
            "repository's own tools/ next to it" % path)
    if str(TOOLS) not in sys.path:
        sys.path.insert(0, str(TOOLS))
    spec = importlib.util.spec_from_file_location("_rtm_%s" % name, path)
    mod = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(mod)
    return mod


def validate_target_table():
    """Fail fast when trace target aliases drift from Wiki identities."""
    identity = _load_tool("hardware_identity")
    errors = identity.target_table_errors(TARGET_TABLE)
    if errors:
        raise SystemExit(
            "config.TARGET_TABLE is inconsistent with hardware identities:\n- "
            + "\n- ".join(errors)
        )


validate_target_table()


def load_wiki_score():
    """The store's own scorer. Imported so scores stay comparable with it.

    Reimplementing the ranking model here would mean a record scored 0.66 by
    this pipeline and 0.71 by the store, with no diff to explain the difference.
    """
    return _load_tool("wiki_score")


def load_store_checker():
    """The store's own gates, for pre-flighting what they would reject."""
    return _load_tool("check_kernel_wiki")


def load_fact_criteria():
    """The established-fact regexes, so the triage here cannot drift from the
    gate that enforces them."""
    return _load_tool("audit_anti_strategy")
