#!/usr/bin/env python3
"""Summarise the staging store into <store>/README.md.

Generated from the records themselves, so it stays accurate instead of drifting as
records accumulate. This is the page a reviewer reads before promoting anything
with `wiki-gate`, so it states what the records claim AND what they may not be
trusted for.

Re-run after every distillation batch, together with score_records.py.

Usage: RTM_TRACE=<trace dir> python3 make_readme.py
"""
import json
import sys
from collections import Counter

import config as c


def load_records():
    out = []
    for p in sorted(c.RECORDS.rglob("*.json")):
        if p.name == "index.json":
            continue
        try:
            out.append((p, json.loads(p.read_text())))
        except json.JSONDecodeError:
            continue
    return out


def load_work():
    """The current trace's work files, when this run produced any."""
    meta_path = c.WORK / "meta.json"
    if not meta_path.is_file():
        return None, [], []
    meta = json.loads(meta_path.read_text())
    versions = [json.loads(l) for l in (c.WORK / "versions.jsonl").open()] \
        if (c.WORK / "versions.jsonl").is_file() else []
    seg_path = c.WORK / "segments.jsonl"
    segments = [json.loads(l) for l in seg_path.open()] \
        if seg_path.is_file() else []
    return meta, versions, segments


def main():
    records = load_records()
    meta_all, versions, segments = load_work()
    meta = (meta_all or {}).get("meta") or {}
    if not records and not meta:
        raise SystemExit(
            "nothing to summarise: no records under %s and no work files under "
            "%s. Run the pipeline first, or point RTM_STORE / RTM_WORKSPACE at "
            "an existing run." % (c.RECORDS, c.WORK))

    w = []
    a = w.append
    a("# Staged optimisation-trace records")
    a("")
    a("Distilled by `skills/opt-trace-mining` from per-kernel optimisation "
      "traces. Generated by `make_readme.py`; do not edit by hand.")
    a("")
    a("**Staging only.** Nothing here is served. `skills/wiki-gate` is the only "
      "writer into `kernel_wiki/records/`: run `--match` for each record, decide "
      "insert / confirm / conflict, then `--commit`. A record that has not been "
      "through the gate is a draft, however green its gates are.")
    a("")

    if meta:
        a("## The trace behind this run")
        a("")
        a("| | |")
        a("|---|---|")
        a("| operator | `%s` |" % meta.get("operator_name"))
        a("| slug / family | `%s` / `%s` |" % (meta.get("operator_slug"),
                                               meta.get("workload_family")))
        a("| trace label | `%s` |" % meta.get("source_repo"))
        a("| HEAD | `%s` |" % (meta.get("head_sha") or "")[:12])
        a("| target | %s / %s / %s |" % (meta.get("vendor"), meta.get("arch"),
                                         meta.get("product")))
        a("| target basis | %s |" % meta.get("arch_basis"))
        a("| harness | %s |" % meta.get("harness"))
        a("| benchmarked shapes | %s |" % meta.get("n_shapes"))
        a("| versions parsed | %d |" % len(versions))
        a("| segments cut | %d |" % len(segments))
        a("")
        if segments:
            kinds = Counter(s["record_type"] for s in segments)
            a("Segments by type: %s. A segment is a candidate, not a record: an "
              "anti-strategy segment whose evidence names no condition and no "
              "mechanism must not be written up at all."
              % ", ".join("%s=%d" % kv for kv in sorted(kinds.items())))
            a("")

    a("## Records")
    a("")
    if not records:
        a("None yet. Distil the packets first "
          "(`references/distill-brief.md`), then re-run `score_records.py` and "
          "this script.")
    else:
        a("```")
        a("records/<type>/<vendor>/<arch>/<dsl>/<operator_family>/<id>.json")
        a("```")
        a("")
        a("The five directory levels agree with the record's own "
          "`retrieval.scope` -- enforced by the layout gate, and the same path "
          "`wiki-gate` derives on insert.")
        a("")
        cells = Counter()
        for _p, r in records:
            scope = (r.get("retrieval") or {}).get("scope") or {}
            cells[(r.get("type"), scope.get("arch"), scope.get("dsl"),
                   scope.get("operator_family"))] += 1
        a("| type | arch | dsl | operator family | records |")
        a("|---|---|---|---|---:|")
        for (t, arch, dsl, fam), n in sorted(cells.items(), key=lambda kv: -kv[1]):
            a("| %s | %s | %s | %s | %d |" % (t, arch, dsl, fam, n))
        a("")
        a("| id tail | type | tier | score | gain | basis | version |")
        a("|---|---|---|---:|---:|---|---|")
        for _p, r in sorted(records, key=lambda kv: kv[1].get("id") or ""):
            worth = r.get("worth") or {}
            gain = worth.get("gain") or {}
            rank = worth.get("rank") or {}
            pct = gain.get("pct")
            regs = (gain.get("regressions") or [{}])[0]
            shown = ("%+.2f%%" % pct) if pct is not None else (
                ("%+.2f%%" % regs["delta_pct"])
                if regs.get("delta_pct") is not None else "-")
            a("| `%s` | %s | %s | %s | %s | %s | `%s` |"
              % ((r.get("id") or "").rsplit(".", 1)[-1], r.get("type"),
                 rank.get("tier"), rank.get("score"), shown,
                 gain.get("basis"),
                 ((r.get("evidence") or {}).get("raw") or {}).get("version")
                 or "-"))
        a("")
        tiers = Counter((r.get("worth") or {}).get("rank", {}).get("tier")
                        for _p, r in records)
        bases = Counter((r.get("worth") or {}).get("gain", {}).get("basis")
                        for _p, r in records)
        a("Tiers: %s. Gain bases: %s."
          % (", ".join("%s=%d" % kv for kv in sorted(tiers.items())),
             ", ".join("%s=%d" % kv for kv in sorted(bases.items()))))
        a("")

    a("## How to read one record")
    a("")
    a("| layer | for whom | content |")
    a("|---|---|---|")
    a("| `retrieval` | the engine | hard scope filter, symptoms, technique tags, "
      "triggers |")
    a("| `payload` | the agent | self-contained: goal, problem, what it was built "
      "on, what changed, the mechanism, the code |")
    a("| `evidence.summary` | the agent | confidence, the harness and GPU the "
      "numbers came from, bottleneck evidence |")
    a("| `evidence.raw` | **humans only** | the trace label, the version and the "
      "commit. Stripped from everything served |")
    a("| `worth` | the agent + ranking | `rank` (score plus tier), `gain` "
      "(percentages only) |")
    a("")

    a("## Trust boundaries")
    a("")
    a("- Provenance is **the trace repository plus the commit**. There is no "
      "markdown page to cite: records are the only source of truth in this "
      "store, and a citation to a file that does not exist is worse than none.")
    a("- No absolute latency appears in `worth.gain`; absolute times live in "
      "`evidence.raw.effect`, which is not served.")
    a("- `worth.gain.basis=measured` means this trace's own harness produced the "
      "number, not that it is comparable with another run's: check "
      "`worth.gain.comparable`.")
    a("- Every number in a record was checked against the packet it was "
      "distilled from (`no-fabrication`), and every code snippet against the "
      "trace's own diff (`verbatim`).")
    a("- An `anti-strategy` here states a fact -- a checkable condition plus a "
      "mechanism -- or it is not here at all.")
    a("")
    a("Per-trace reports live in `reports/<slug>/`: `recon.md` says what a trace "
      "could honestly yield, `partition.md` says how each record was cut. The "
      "record shape is `schema/kernel/schema.json`, narrowed for this corpus by "
      "`skills/opt-trace-mining/assets/schema/%s.schema.json`." % c.PROFILE_NAME)
    a("")

    path = c.STORE / "README.md"
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text("\n".join(w) + "\n")
    print("records %d -> %s" % (len(records), path))
    return 0


if __name__ == "__main__":
    sys.exit(main())
