#!/usr/bin/env python3
"""Summarise a finished store into kernel_wiki/session_trace/<set>/README.md.

Generated from the records and the work files, so it stays accurate instead of
drifting as records accumulate. Re-run after every distillation batch.

Usage: STM_SET=<name> python3 make_readme.py
"""
import json
import sys
from collections import Counter

import config as c


def load(set_name):
    work = c.work(set_name)
    meta = json.loads((work / "meta.json").read_text())
    rows = [json.loads(l) for l in (work / "versions.jsonl").open()]
    seg_path = work / "segments.jsonl"
    segs = [json.loads(l) for l in seg_path.open()] if seg_path.is_file() else []
    recs = []
    for p in sorted(c.records(set_name).rglob("*.json")):
        if p.name == "index.json":
            continue
        try:
            recs.append((p, json.loads(p.read_text())))
        except json.JSONDecodeError:
            continue
    return meta, rows, segs, recs


def main():
    set_name, cfg, _root = c.require_set()
    meta, rows, segs, recs = load(set_name)

    w = []
    a = w.append
    a("# %s session optimization experience store" % set_name)
    a("")
    a("Distilled by `skills/session-trace-mining` from the session transcripts of "
      "an AI coding agent. This file is generated by `make_readme.py`; do not "
      "hand-edit it.")
    a("")
    a("## Corpus")
    a("")
    a("- Session files: %d main transcripts + %d sub-agent transcripts, %d failed to parse"
      % (meta["n_transcripts"], meta["n_subagent_transcripts"],
         meta["n_unparsed"]))
    a("- Transcript formats: %s; candidate unit: `%s`" % (meta["formats"], meta["unit"]))
    a("- Operators (taken from the session working directory): %s" % meta["operators"])
    a("- Hardware / DSLs detected: %s / %s"
      % (meta["products_detected"], meta["dsls_detected"]))
    a("- %d candidates, %d segments cut, **%d** records distilled, schema `%s`"
      % (len(rows), len(segs), len(recs), c.DERIVED_NAME))
    if meta.get("note"):
        a("")
        a("> %s" % meta["note"])
    a("")

    a("## How records are organized")
    a("")
    a("```")
    a("records/<type>/<vendor>/<arch>/<dsl>/<operator_family>/<id>.json")
    a("```")
    a("")
    a("The four directory levels agree strictly with the record's own "
      "`retrieval.scope` (enforced by the layout gate), so a record can be "
      "addressed directly by type, architecture, DSL and operator family.")
    a("")

    if recs:
        cells = Counter()
        for _p, r in recs:
            sc = (r.get("retrieval") or {}).get("scope") or {}
            gen = (r.get("retrieval") or {}).get("generality") or {}
            cells[(r.get("type"), sc.get("arch"), sc.get("dsl"),
                   gen.get("workload_family"))] += 1
        a("| type | arch | dsl | family | Records |")
        a("|---|---|---|---|---:|")
        for (t, arch, dsl, fam), n in sorted(cells.items(),
                                             key=lambda kv: -kv[1]):
            a("| %s | %s | %s | %s | %d |" % (t, arch, dsl, fam, n))
        a("")

        a("## Record list")
        a("")
        a("| id tail | type | tier | Gain | Basis | Shapes |")
        a("|---|---|---|---:|---|---:|")
        for _p, r in sorted(recs, key=lambda kv: kv[1].get("id") or ""):
            worth = r.get("worth") or {}
            gain = worth.get("gain") or {}
            rank = worth.get("rank") or {}
            reg = (gain.get("regressions") or [{}])[0]
            pct = gain.get("pct")
            shown = ("%.2f%%" % pct) if pct is not None else (
                ("%.2f%%" % reg["delta_pct"]) if reg.get("delta_pct") is not None
                else "—")
            n_shapes = ((r.get("payload") or {}).get("problem") or {}).get(
                "shape_contract", {}).get("n_benchmarked_shapes")
            a("| `%s` | %s | %s | %s | %s | %s |"
              % ((r.get("id") or "").rsplit(".", 1)[-1], r.get("type"),
                 rank.get("tier"), shown, gain.get("basis"), n_shapes or "—"))
        a("")

        tiers = Counter((r.get("worth") or {}).get("rank", {}).get("tier")
                        for _p, r in recs)
        bases = Counter((r.get("worth") or {}).get("gain", {}).get("basis")
                        for _p, r in recs)
        a("| tier | Records | | basis | Records |")
        a("|---|---:|---|---|---:|")
        keys = list(tiers) + [None] * max(0, len(bases) - len(tiers))
        bkeys = list(bases) + [None] * max(0, len(tiers) - len(bases))
        for tk, bk in zip(keys, bkeys):
            a("| %s | %s | | %s | %s |"
              % (tk or "", tiers.get(tk, "") if tk else "",
                 bk or "", bases.get(bk, "") if bk else ""))
        a("")

    a("## How to read a record")
    a("")
    a("| Layer | For whom | Contents |")
    a("|---|---|---|")
    a("| `retrieval` | the retrieval engine | Scope hard filters, symptoms, technique tags, trigger situations |")
    a("| `payload` | agent | Self-contained: the goal, the problem, which "
      "approach it improves on, what the change is, the mechanism |")
    a("| `evidence.summary` | agent | Confidence, measurement environment, bottleneck evidence |")
    a("| `evidence.raw` | **humans only** | Session provenance: corpus set "
      "name, relative path, line numbers, line digests |")
    a("| `worth` | agent + ranking | `rank` (score + confidence class), `gain` (percentages only) |")
    a("")

    a("## Limits of confidence")
    a("")
    a("- Numbers fall into three tiers: **T1** is tool output from a benchmark / "
      "profiler, **T2** is the agent reading back notes it wrote itself, and "
      "**T3** is a structured field the agent wrote. `gain.basis=measured` is only "
      "allowed when a T1 block exists (enforced by the `evidence-tier` gate).")
    a("- Agent prose and the orchestration prompt **do not enter the evidence "
      "pool**: the first would let a number the agent invented become its own "
      "evidence, and the second states the target percentage.")
    a("- `gain.comparable` is always false: this is a sibling run and is not "
      "comparable with the main store's main chain.")
    a("- There are no absolute times in `worth.gain`; absolute values live only in "
      "`evidence.raw.effect` and are stripped when served.")
    a("- A version that collides with the main store on `(operator, version)` is "
      "**skipped outright**; this set skipped %d."
      % len(meta.get("wiki_skipped") or []))
    a("")
    a("See `reports/recon.md` (what this corpus can honestly yield) and "
      "`reports/partition.md` (how each record was cut) for detail; the schema is "
      "at `skills/session-trace-mining/assets/schema/%s.schema.json`."
      % c.DERIVED_NAME)
    a("")

    path = c.store(set_name) / "README.md"
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text("\n".join(w) + "\n")
    print("records %d -> %s" % (len(recs), path))
    return 0


if __name__ == "__main__":
    sys.exit(main())
