#!/usr/bin/env python3
"""Evidence-density report: what this set can honestly yield.

Runs before any LLM is involved, because the shape of the corpus decides the
shape of the product. Three numbers have veto power:

  citable share    how many candidates have a number in a T1 tool output rather
                   than only in the agent's own notes. Below that line a record
                   may not claim `basis: measured`.
  diff coverage    how many have a verbatim diff. A candidate with none may not
                   become a `strategy` record at all, because such a record is
                   schema-required to carry an implementation.
  already covered  how many versions the committed stores already hold for this
                   operator. Those are skipped outright, and if the overlap is
                   most of the set there is little to add.

Usage: STM_SET=<name> python3 recon.py
"""
import json
import sys
from collections import Counter

import config as c


def load(set_name):
    work = c.work(set_name)
    rows = [json.loads(l) for l in (work / "versions.jsonl").open()]
    meta = json.loads((work / "meta.json").read_text())
    return rows, meta


def tier_of(row):
    tiers = set((row.get("number_tiers") or {}).values())
    for t in ("T1", "T2", "T3"):
        if t in tiers:
            return t
    return None


def classify(rows, unit):
    """What each candidate could become, before any agent sees it."""
    out = Counter()
    for r in rows:
        if r.get("implausible"):
            out["implausible"] += 1
            continue
        if unit == "version-ladder":
            if r.get("reverted"):
                out["anti-strategy (reverted)"] += 1
            elif not r.get("geomean_us"):
                out["no metric"] += 1
            elif not r.get("sha"):
                out["no commit"] += 1
            else:
                out["strategy candidate"] += 1
        else:
            if r["improve_pct_raw"] <= 0:
                out["anti-strategy (regression)"] += 1
            elif r.get("diff_coverage") == "blind":
                out["blind (no diff)"] += 1
            else:
                out["strategy candidate"] += 1
    return out


def existing_coverage(rows):
    """Which operators in this set the committed store already writes about."""
    ops = {r.get("operator_id") for r in rows if r.get("operator_id")}
    hits = {}
    for root in c.COMMITTED_STORES:
        if not root.is_dir():
            continue
        for path in root.rglob("*.json"):
            if path.name == "index.json":
                continue
            try:
                rec = json.loads(path.read_text())
            except (json.JSONDecodeError, OSError):
                continue
            raw = (rec.get("evidence") or {}).get("raw") or {}
            repo = str(raw.get("source_repo") or "")
            for op in ops:
                if op and op in repo:
                    hits.setdefault(op, []).append(
                        (rec.get("id"), raw.get("version")))
    return hits


def main():
    set_name, cfg, _root = c.require_set()
    rows, meta = load(set_name)
    unit = meta["unit"]
    kinds = classify(rows, unit)
    tiers = Counter(tier_of(r) for r in rows)
    coverage = existing_coverage(rows)

    w = []
    a = w.append
    a("# Evidence-density report: %s" % set_name)
    a("")
    a("Generated by `recon.py`. **Read this report before deciding what to "
      "distill** -- the shape of the corpus decides the shape of the product.")
    a("")
    a("## Corpus")
    a("")
    a("| | |")
    a("|---|---|")
    a("| Session files | %d main + %d sub-agent |"
      % (meta["n_transcripts"], meta["n_subagent_transcripts"]))
    a("| Failed to parse | %d |" % meta["n_unparsed"])
    a("| Transcript formats | %s |" % meta["formats"])
    a("| Candidate unit | `%s` |" % unit)
    a("| Products detected | %s |" % meta["products_detected"])
    a("| DSLs detected | %s |" % meta["dsls_detected"])
    a("| Operators (taken from cwd) | %s |" % meta["operators"])
    a("")
    a("Declared defaults: %s. Detection wins over declaration; `arch_basis` "
      "records which source each candidate actually relied on."
      % meta["declared"])
    a("")
    if meta.get("note"):
        a("> %s" % meta["note"])
        a("")

    if unit == "version-ladder":
        a("## Version ladder")
        a("")
        a("| | |")
        a("|---|---:|")
        a("| Versions echoed by `git log` | %d |" % meta["ladder_versions"])
        a("| Versions attributable to a session | %d |"
          % meta["sessions_owning_a_version"])
        a("| Sessions yielding no version (planning/profiling/research) | %d |"
          % meta["sessions_without_version"])
        a("| Candidate rows | %d |" % len(rows))
        a("| ...with a geomean | %d |"
          % sum(1 for r in rows if r.get("geomean_us")))
        a("| ...with a commit | %d |" % sum(1 for r in rows if r.get("sha")))
        a("| ...reverted | %d |" % sum(1 for r in rows if r.get("reverted")))
        a("")
        a("One session is usually one version: the orchestration prompt often "
          "confines each session to a single optimization cycle, so the ladder "
          "exists only at the scale of the **whole corpus** and cannot be seen "
          "inside a single file. A session that yields no version is not a parse "
          "failure but a planning or profiling session, and it serves as packet "
          "evidence for the version it discusses.")
        a("")
    else:
        a("## A/B candidates")
        a("")
        by_basis = Counter(r["delta_basis"] for r in rows)
        a("| Source | Count |")
        a("|---|---:|")
        for k, n in by_basis.most_common():
            a("| `%s` | %d |" % (k, n))
        a("| **Total** | **%d** |" % len(rows))
        a("")
        a("This corpus has no version ladder, so the candidate unit is **one "
          "measured A/B**. Among them, `*-variant` is a comparison the transcript "
          "already contains (both sides printed by the same output), while "
          "`before-after` is the same benchmark command run once before and once "
          "after a change. The latter barely exists in this corpus: every "
          "run uses a freshly written inline script, and one transcript was "
          "measured to hold 61 distinct benchmark identities and 0 repeats.")
        a("")

    a("## Distillable pool")
    a("")
    a("| Class | Count |")
    a("|---|---:|")
    for k, n in kinds.most_common():
        a("| %s | %d |" % (k, n))
    a("")

    a("## Trust tiers for the numbers")
    a("")
    a("| Tier | Meaning | Candidates | `gain.basis` ceiling |")
    a("|---|---|---:|---|")
    a("| T1 | Tool output from a benchmark / profiler | %d | `measured` |"
      % tiers.get("T1", 0))
    a("| T2 | The agent reading back notes it wrote itself (`cat NOTES.md`, `git log`, `Read vN.json`) | %d | `reported` |"
      % tiers.get("T2", 0))
    a("| T3 | A structured field the agent wrote directly | %d | `reported` |"
      % tiers.get("T3", 0))
    a("| — | No quotable number | %d | `qualitative` |" % tiers.get(None, 0))
    a("")
    a("T4 (agent prose and thinking) and T5 (the orchestration prompt) **do not "
      "enter the evidence pool**: the first would let a number the agent invented "
      "become its own evidence, and the second states the target percentage, "
      "which would issue a pass to any claim landing near the threshold.")
    a("")

    a("## diff visibility")
    a("")
    cov = Counter(r.get("diff_coverage") for r in rows)
    a("| Coverage | Count | Consequence |")
    a("|---|---:|---|")
    a("| `full` (a verbatim diff exists) | %d | May become a `strategy` |"
      % cov.get("full", 0))
    a("| `partial` | %d | May become a `strategy`; the snippet needs human confirmation |"
      % cov.get("partial", 0))
    a("| `blind` (the change left no diff) | %d | **May not** become a `strategy` |"
      % cov.get("blind", 0))
    a("")
    a("The blind spot comes from shell file writes (`cat >`/`tee`): a change made "
      "that way produces no patch event. The `diff-coverage` gate books it rather "
      "than letting it pass unnoticed.")
    a("")

    a("## Overlap with the main store")
    a("")
    skipped = meta.get("wiki_skipped") or []
    a("Per the user's decision: **a colliding version is skipped outright**, "
      "without even generating a packet.")
    a("")
    a("| | |")
    a("|---|---:|")
    a("| Versions skipped as already covered by the main store | %d |"
      % len(skipped))
    a("")
    if skipped:
        a("| Version | Existing record |")
        a("|---|---|")
        for s in skipped:
            a("| `%s` | `%s` |" % (s["dedup_key"],
                                   ", ".join(str(x) for x in s["covered_by"][:2])))
        a("")
    if coverage:
        a("Records the main store already holds for this set's operators (same "
          "operator, possibly a different run):")
        a("")
        for op, recs in sorted(coverage.items()):
            vers = sorted({str(v) for _i, v in recs if v})
            a("- `%s`: %d records, versions %s"
              % (op, len(recs), ", ".join(vers[:14])))
        a("")

    a("## Archive entries excluded")
    a("")
    a("| Entry | Reason |")
    a("|---|---|")
    for name, why in sorted(meta.get("excluded_from_archive", {}).items()):
        a("| `%s` | %s |" % (name, why))
    a("")

    path = c.reports(set_name) / "recon.md"
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text("\n".join(w) + "\n")

    print("set        %s (%s)" % (set_name, unit))
    print("candidates %d" % len(rows))
    for k, n in kinds.most_common():
        print("  %-28s %d" % (k, n))
    print("tiers      %s" % {str(k): v for k, v in tiers.items()})
    print("diff       %s" % {str(k): v for k, v in cov.items()})
    print("-> %s" % path)
    return 0


if __name__ == "__main__":
    sys.exit(main())
